# Inlämning 2: Numpy, Pandas och Analys

### Part 1: Numpy

In [ ]:
import numpy as np

Konstruera en array med 10 kolumner och 5 rader av float-tal. Inget tal får vara samma.

In [ ]:
N = 50
xa = np.linspace(0, 1, N, endpoint=False)
arr = np.array(xa)
x1 = arr.reshape(5,10)
print(x1)

[[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18]
 [0.2  0.22 0.24 0.26 0.28 0.3  0.32 0.34 0.36 0.38]
 [0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54 0.56 0.58]
 [0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78]
 [0.8  0.82 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]]


Konstruera en ny array till med 10 kolumner och 7 rader av float-tal. Den skall inte vara samma som ovan array..

In [ ]:
N = 70
xb = np.linspace(1, 2, N, endpoint=False)
arr = np.array(xb)
x2 = arr.reshape(7,10)
print(x2)

[[1.         1.01428571 1.02857143 1.04285714 1.05714286 1.07142857
  1.08571429 1.1        1.11428571 1.12857143]
 [1.14285714 1.15714286 1.17142857 1.18571429 1.2        1.21428571
  1.22857143 1.24285714 1.25714286 1.27142857]
 [1.28571429 1.3        1.31428571 1.32857143 1.34285714 1.35714286
  1.37142857 1.38571429 1.4        1.41428571]
 [1.42857143 1.44285714 1.45714286 1.47142857 1.48571429 1.5
  1.51428571 1.52857143 1.54285714 1.55714286]
 [1.57142857 1.58571429 1.6        1.61428571 1.62857143 1.64285714
  1.65714286 1.67142857 1.68571429 1.7       ]
 [1.71428571 1.72857143 1.74285714 1.75714286 1.77142857 1.78571429
  1.8        1.81428571 1.82857143 1.84285714]
 [1.85714286 1.87142857 1.88571429 1.9        1.91428571 1.92857143
  1.94285714 1.95714286 1.97142857 1.98571429]]


Gör om de ovan arrayerna så att de har 5 kolumner men innehåller samma data.

In [8]:
N = 50
x = np.linspace(0, 1, N, endpoint=True)
arr = np.array(x)
x1 = arr.reshape(10,5)
print(x1)

N = 70
x = np.linspace(1, 2, N, endpoint=True)
arr = np.array(x)
x2 = arr.reshape(14,5)
print(x2)

[[0.         0.02040816 0.04081633 0.06122449 0.08163265]
 [0.10204082 0.12244898 0.14285714 0.16326531 0.18367347]
 [0.20408163 0.2244898  0.24489796 0.26530612 0.28571429]
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551 ]
 [0.40816327 0.42857143 0.44897959 0.46938776 0.48979592]
 [0.51020408 0.53061224 0.55102041 0.57142857 0.59183673]
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755]
 [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837]
 [0.81632653 0.83673469 0.85714286 0.87755102 0.89795918]
 [0.91836735 0.93877551 0.95918367 0.97959184 1.        ]]
[[1.         1.01449275 1.02898551 1.04347826 1.05797101]
 [1.07246377 1.08695652 1.10144928 1.11594203 1.13043478]
 [1.14492754 1.15942029 1.17391304 1.1884058  1.20289855]
 [1.2173913  1.23188406 1.24637681 1.26086957 1.27536232]
 [1.28985507 1.30434783 1.31884058 1.33333333 1.34782609]
 [1.36231884 1.37681159 1.39130435 1.4057971  1.42028986]
 [1.43478261 1.44927536 1.46376812 1.47826087 1.49275362]
 [1.50724638 

Slå ihop de bägge arrayerna till en array.

In [9]:
x3 = np.concatenate((x1, x2), axis=0)
print(x3)

[[0.         0.02040816 0.04081633 0.06122449 0.08163265]
 [0.10204082 0.12244898 0.14285714 0.16326531 0.18367347]
 [0.20408163 0.2244898  0.24489796 0.26530612 0.28571429]
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551 ]
 [0.40816327 0.42857143 0.44897959 0.46938776 0.48979592]
 [0.51020408 0.53061224 0.55102041 0.57142857 0.59183673]
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755]
 [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837]
 [0.81632653 0.83673469 0.85714286 0.87755102 0.89795918]
 [0.91836735 0.93877551 0.95918367 0.97959184 1.        ]
 [1.         1.01449275 1.02898551 1.04347826 1.05797101]
 [1.07246377 1.08695652 1.10144928 1.11594203 1.13043478]
 [1.14492754 1.15942029 1.17391304 1.1884058  1.20289855]
 [1.2173913  1.23188406 1.24637681 1.26086957 1.27536232]
 [1.28985507 1.30434783 1.31884058 1.33333333 1.34782609]
 [1.36231884 1.37681159 1.39130435 1.4057971  1.42028986]
 [1.43478261 1.44927536 1.46376812 1.47826087 1.49275362]
 [1.50724638 1

Ändra ordningen på kolumnerna så att de har ordningen kolumn5, kolumn3, kolumn4, kolumn1 och kolumn2.

In [10]:
permutation = [4, 2, 3, 0, 1]
idx = np.empty_like(permutation)
idx[permutation] = np.arange(len(permutation))
x3[:, idx]  # return a rearranged copy
x3[:] = x3[:, idx]  # in-place modification of a
print(x3)

[[0.06122449 0.08163265 0.02040816 0.04081633 0.        ]
 [0.16326531 0.18367347 0.12244898 0.14285714 0.10204082]
 [0.26530612 0.28571429 0.2244898  0.24489796 0.20408163]
 [0.36734694 0.3877551  0.32653061 0.34693878 0.30612245]
 [0.46938776 0.48979592 0.42857143 0.44897959 0.40816327]
 [0.57142857 0.59183673 0.53061224 0.55102041 0.51020408]
 [0.67346939 0.69387755 0.63265306 0.65306122 0.6122449 ]
 [0.7755102  0.79591837 0.73469388 0.75510204 0.71428571]
 [0.87755102 0.89795918 0.83673469 0.85714286 0.81632653]
 [0.97959184 1.         0.93877551 0.95918367 0.91836735]
 [1.04347826 1.05797101 1.01449275 1.02898551 1.        ]
 [1.11594203 1.13043478 1.08695652 1.10144928 1.07246377]
 [1.1884058  1.20289855 1.15942029 1.17391304 1.14492754]
 [1.26086957 1.27536232 1.23188406 1.24637681 1.2173913 ]
 [1.33333333 1.34782609 1.30434783 1.31884058 1.28985507]
 [1.4057971  1.42028986 1.37681159 1.39130435 1.36231884]
 [1.47826087 1.49275362 1.44927536 1.46376812 1.43478261]
 [1.55072464 1

### Part 2: Panda

In [27]:
import pandas as pd

Hur många regioner finns med i data?
Lista regionerna i bokstavsordning
Vad är invånarantalet i varje region
Hur många brott begicks i varje region
Skapa en dataframe på de områden  med de 10 högsta antalet överfall.
Lägg till en kolumn i dataframen som visar % antal överfall i området jämfört med invånarantal i området
Skapa en ny dataframe som innehåller antalet områden som finns av de olika typerna av urban area. Ledtråd: groupby
Ta reda på hur många områden hade population men inga överfall. Jämfört totala populationen i dessa med totala poplulationen i deras region.
Räkna antalet områden som inte har någon data på överfall eller invånare.
VG: Skapa en ny dataframe med 10  områderna med mer än 5000 invånare, men har de lägsta överfallen per invånare. 
VG: Skapa en ny dataframe som innehåller % överfall i regionen jämfört med antalet invånare i regionen.  
VG: Lägg till en ny kolumn i dataframen som visar % antal överfall per region


In [56]:
assults = pd.read_csv('assults.csv')
print("Hur många regioner finns med i data?: ",len(assults.drop_duplicates('Region_2013_label')))
assults.drop_duplicates('Region_2013_label')

Hur många regioner finns med i data?:  17


Index  Area_unit_2013_code             Area_unit_2013_label  \
0         1               514102            Auckland Central West   
1         2               573101  Willis Street-Cambridge Terrace   
2         3               529700                 Hamilton Central   
4         5               591500                 Cathedral Square   
7         8               562800         Palmerston North Central   
8         9               540410                           Kuirau   
10       11               603100           Stuart St-Frederick St   
12       13               582500                        Trafalgar   
13       14               548200                 Hastings Central   
14       15               544600                 Gisborne Central   
22       23               551800             New Plymouth Central   
26       27               581230                 Blenheim Central   
31       32               503100                Whangarei Central   
43       44               611210                     Otakaro Park   
149     150               584301                     Motueka West   
328     329               585140                  Greymouth South   
1615   1616               666670           Oceanic-Snares Islands   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   550                      15900   
1                                   447                       8300   
2                                   380                       3170   
4                                   305                        570   
7                                   190                       3060   
8                                   168                       1290   
10                                  154                       3360   
12                                  138                        550   
13                                  130                       2970   
14                                  128                       3380   
22                                  102                        680   
26                                   91                       2790   
31                                   87                        280   
43                                   73                        820   
149                                  34                       3890   
328                                  20                       2850   
1615                                  0                          0   

      Rate_per_10000_population   Rate_ratio_NZ_average_rate   \
0                            346                          6.6   
1                            539                         10.3   
2                          1,199                         22.9   
4                          5,351                        102.3   
7                            621                         11.9   
8                          1,302                         24.9   
10                           458                          8.8   
12                         2,509                           48   
13                           438                          8.4   
14                           379                          7.2   
22                         1,500                         28.7   
26                           326                          6.2   
31                         3,107                         59.4   
43                           890                           17   
149                           87                          1.7   
328                           70                          1.3   
1615                        -                            -      

      Urban_area_2013_code  Urban_area_2013_label       Urban_area_type  \
0                        4  Central Auckland Zone       Main urban area   
1                       20        Wellington Zone       Main urban area   
2                        6          Hamilton Zone       Main urban area   
4                       22     

### Part 3: Utforskning/analys

Minst 500 rader, 5 Kolumner i ditt valda dataset

#### Step 1: Välj dataset

Hitta ett intressant dataset. Det valda datasettet måste vara i CSV format,  ha minst 500 rader och 5 kolumner. 
Ladda ner datasetet med pandas read_csv funktion och en url (se nedan). Alternativt i inlämningen skicka med datasettet.

In [58]:
url = 'https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv'
data = pd.read_csv(url)

#### Step 2: Data preparation och Cleaning

Ladda in dataset in i en dataframe med pandas. 
Behandla missade data, icke-korrekt data och fel data.
Gör andra steg som behövs (gör om sträng datum till riktiga datum, skapa fler kolumner, slå ihop datasets osv).
Summera hur datasetet ser ut i nuvarande läge i dina markdowns. Storlek, kolumner, kategori typer (qualitative vs. quantitative), kvalitet på data, fång osv.

#### Step 3: Undersökande analys och visualisering

Undersök data genom analysera (mean, sum, range osv)  intressant statistik i numeriska kolumnerna.
Undersök distributions av numeriska kolumner genom histogram osv
Undersök relationen mellan kolumner med scatter plots, bar chars osv.
Notera intressanta upptäckter i din markdown.

#### Step 4: För VG - fråga och svara på 4 intressanta frågor om datan

#### Step 5: Summera dina slutsatser & Skriv ett avslut.