# Inlämning 2: Numpy, Pandas och Analys

### Part 1: Numpy

In [2]:
import numpy as np

Konstruera en array med 10 kolumner och 5 rader av float-tal. Inget tal får vara samma.

In [35]:
N = 50
x = np.linspace(0, 1, N, endpoint=False)
arr = np.array(x)
x1 = arr.reshape(5,10)
print(x1)

[[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18]
 [0.2  0.22 0.24 0.26 0.28 0.3  0.32 0.34 0.36 0.38]
 [0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54 0.56 0.58]
 [0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78]
 [0.8  0.82 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]]


Konstruera en ny array till med 10 kolumner och 7 rader av float-tal. Den skall inte vara samma som ovan array..

In [34]:
N = 70
x = np.linspace(1, 2, N, endpoint=False)
arr = np.array(x)
x2 = arr.reshape(7,10)
print(x2)

[[1.         1.01428571 1.02857143 1.04285714 1.05714286 1.07142857
  1.08571429 1.1        1.11428571 1.12857143]
 [1.14285714 1.15714286 1.17142857 1.18571429 1.2        1.21428571
  1.22857143 1.24285714 1.25714286 1.27142857]
 [1.28571429 1.3        1.31428571 1.32857143 1.34285714 1.35714286
  1.37142857 1.38571429 1.4        1.41428571]
 [1.42857143 1.44285714 1.45714286 1.47142857 1.48571429 1.5
  1.51428571 1.52857143 1.54285714 1.55714286]
 [1.57142857 1.58571429 1.6        1.61428571 1.62857143 1.64285714
  1.65714286 1.67142857 1.68571429 1.7       ]
 [1.71428571 1.72857143 1.74285714 1.75714286 1.77142857 1.78571429
  1.8        1.81428571 1.82857143 1.84285714]
 [1.85714286 1.87142857 1.88571429 1.9        1.91428571 1.92857143
  1.94285714 1.95714286 1.97142857 1.98571429]]


Gör om de ovan arrayerna så att de har 5 kolumner men innehåller samma data.

In [65]:
x3 = np.full((10, 5), 10)
print(x3)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


Slå ihop de bägge arrayerna till en array.

In [66]:
#x4 = np.concatenate((x1, x3), axis=0)
x4 = x3*x1
print(x4)

ValueError: operands could not be broadcast together with shapes (10,5) (5,10) 

Ändra ordningen på kolumnerna så att de har ordningen kolumn5, kolumn3, kolumn4, kolumn1 och kolumn2.

In [56]:
permutation = [0, 4, 1, 3, 2, 5, 8, 6, 9, 7]
idx = np.empty_like(permutation)
idx[permutation] = np.arange(len(permutation))
x4[:, idx]  # return a rearranged copy
x5 = x4[:] = x4[:, idx]  # in-place modification of x4
print(x5)

[[0.  0.4 0.8 0.6 0.2 1.  1.4 1.8 1.2 1.6]
 [2.  2.4 2.8 2.6 2.2 3.  3.4 3.8 3.2 3.6]
 [4.  4.4 4.8 4.6 4.2 5.  5.4 5.8 5.2 5.6]
 [6.  6.4 6.8 6.6 6.2 7.  7.4 7.8 7.2 7.6]
 [8.  8.4 8.8 8.6 8.2 9.  9.4 9.8 9.2 9.6]]


### Part 2: Panda

In [2]:
import pandas as pd

In [3]:
assults = pd.read_csv('assults.csv')

Hur många regioner finns med i data?
Lista regionerna i bokstavsordning
Vad är invånarantalet i varje region
Hur många brott begicks i varje region
Skapa en dataframe på de områden  med de 10 högsta antalet överfall.
Lägg till en kolumn i dataframen som visar % antal överfall i området jämfört med invånarantal i området
Skapa en ny dataframe som innehåller antalet områden som finns av de olika typerna av urban area. Ledtråd: groupby
Ta reda på hur många områden hade population men inga överfall. Jämfört totala populationen i dessa med totala poplulationen i deras region.
Räkna antalet områden som inte har någon data på överfall eller invånare.
VG: Skapa en ny dataframe med 10  områderna med mer än 5000 invånare, men har de lägsta överfallen per invånare. 
VG: Skapa en ny dataframe som innehåller % överfall i regionen jämfört med antalet invånare i regionen.  
VG: Lägg till en ny kolumn i dataframen som visar % antal överfall per region


### Part 3: Utforskning/analys

Minst 500 rader, 5 Kolumner i ditt valda dataset

#### Step 1: Välj dataset

Hitta ett intressant dataset. Det valda datasettet måste vara i CSV format,  ha minst 500 rader och 5 kolumner. 
Ladda ner datasetet med pandas read_csv funktion och en url (se nedan). Alternativt i inlämningen skicka med datasettet.

In [ ]:
url = 'https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv'
data = pd.read_csv(url)

#### Step 2: Data preparation och Cleaning

Ladda in dataset in i en dataframe med pandas. 
Behandla missade data, icke-korrekt data och fel data.
Gör andra steg som behövs (gör om sträng datum till riktiga datum, skapa fler kolumner, slå ihop datasets osv).
Summera hur datasetet ser ut i nuvarande läge i dina markdowns. Storlek, kolumner, kategori typer (qualitative vs. quantitative), kvalitet på data, fång osv.

#### Step 3: Undersökande analys och visualisering

Undersök data genom analysera (mean, sum, range osv)  intressant statistik i numeriska kolumnerna.
Undersök distributions av numeriska kolumner genom histogram osv
Undersök relationen mellan kolumner med scatter plots, bar chars osv.
Notera intressanta upptäckter i din markdown.

#### Step 4: För VG - fråga och svara på 4 intressanta frågor om datan

#### Step 5: Summera dina slutsatser & Skriv ett avslut.