# Inlämning 2: Numpy, Pandas och Analys

### Part 1: Numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Konstruera en array med 10 kolumner och 5 rader av float-tal. Inget tal får vara samma.

In [2]:
N = 50
xa = np.linspace(0, 1, N, endpoint=False)
arr = np.array(xa)
x1 = arr.reshape(5,10)
print(x1)

[[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18]
 [0.2  0.22 0.24 0.26 0.28 0.3  0.32 0.34 0.36 0.38]
 [0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54 0.56 0.58]
 [0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78]
 [0.8  0.82 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]]


Konstruera en ny array till med 10 kolumner och 7 rader av float-tal. Den skall inte vara samma som ovan array..

In [3]:
N = 70
xb = np.linspace(1, 2, N, endpoint=False)
arr = np.array(xb)
x2 = arr.reshape(7,10)
print(x2)

[[1.         1.01428571 1.02857143 1.04285714 1.05714286 1.07142857
  1.08571429 1.1        1.11428571 1.12857143]
 [1.14285714 1.15714286 1.17142857 1.18571429 1.2        1.21428571
  1.22857143 1.24285714 1.25714286 1.27142857]
 [1.28571429 1.3        1.31428571 1.32857143 1.34285714 1.35714286
  1.37142857 1.38571429 1.4        1.41428571]
 [1.42857143 1.44285714 1.45714286 1.47142857 1.48571429 1.5
  1.51428571 1.52857143 1.54285714 1.55714286]
 [1.57142857 1.58571429 1.6        1.61428571 1.62857143 1.64285714
  1.65714286 1.67142857 1.68571429 1.7       ]
 [1.71428571 1.72857143 1.74285714 1.75714286 1.77142857 1.78571429
  1.8        1.81428571 1.82857143 1.84285714]
 [1.85714286 1.87142857 1.88571429 1.9        1.91428571 1.92857143
  1.94285714 1.95714286 1.97142857 1.98571429]]


Gör om de ovan arrayerna så att de har 5 kolumner men innehåller samma data.

In [4]:
N = 50
x = np.linspace(0, 1, N, endpoint=True)
arr = np.array(x)
x1 = arr.reshape(10,5)
print(x1)

N = 70
x = np.linspace(1, 2, N, endpoint=True)
arr = np.array(x)
x2 = arr.reshape(14,5)
print(x2)

[[0.         0.02040816 0.04081633 0.06122449 0.08163265]
 [0.10204082 0.12244898 0.14285714 0.16326531 0.18367347]
 [0.20408163 0.2244898  0.24489796 0.26530612 0.28571429]
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551 ]
 [0.40816327 0.42857143 0.44897959 0.46938776 0.48979592]
 [0.51020408 0.53061224 0.55102041 0.57142857 0.59183673]
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755]
 [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837]
 [0.81632653 0.83673469 0.85714286 0.87755102 0.89795918]
 [0.91836735 0.93877551 0.95918367 0.97959184 1.        ]]
[[1.         1.01449275 1.02898551 1.04347826 1.05797101]
 [1.07246377 1.08695652 1.10144928 1.11594203 1.13043478]
 [1.14492754 1.15942029 1.17391304 1.1884058  1.20289855]
 [1.2173913  1.23188406 1.24637681 1.26086957 1.27536232]
 [1.28985507 1.30434783 1.31884058 1.33333333 1.34782609]
 [1.36231884 1.37681159 1.39130435 1.4057971  1.42028986]
 [1.43478261 1.44927536 1.46376812 1.47826087 1.49275362]
 [1.50724638 

Slå ihop de bägge arrayerna till en array.

In [5]:
x3 = np.concatenate((x1, x2), axis=0)
print(x3)

[[0.         0.02040816 0.04081633 0.06122449 0.08163265]
 [0.10204082 0.12244898 0.14285714 0.16326531 0.18367347]
 [0.20408163 0.2244898  0.24489796 0.26530612 0.28571429]
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551 ]
 [0.40816327 0.42857143 0.44897959 0.46938776 0.48979592]
 [0.51020408 0.53061224 0.55102041 0.57142857 0.59183673]
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755]
 [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837]
 [0.81632653 0.83673469 0.85714286 0.87755102 0.89795918]
 [0.91836735 0.93877551 0.95918367 0.97959184 1.        ]
 [1.         1.01449275 1.02898551 1.04347826 1.05797101]
 [1.07246377 1.08695652 1.10144928 1.11594203 1.13043478]
 [1.14492754 1.15942029 1.17391304 1.1884058  1.20289855]
 [1.2173913  1.23188406 1.24637681 1.26086957 1.27536232]
 [1.28985507 1.30434783 1.31884058 1.33333333 1.34782609]
 [1.36231884 1.37681159 1.39130435 1.4057971  1.42028986]
 [1.43478261 1.44927536 1.46376812 1.47826087 1.49275362]
 [1.50724638 1

Ändra ordningen på kolumnerna så att de har ordningen kolumn5, kolumn3, kolumn4, kolumn1 och kolumn2.

In [30]:
b = np.array(x3)
print(b[:, [4,2,3,0,1]])

# eller om man använder pandas

import pandas as pd
#initializing pandas dataframe
df = pd.DataFrame(x3.reshape(-1, 5), columns=list('12345'))
#changing order of column
df = df[list('53412')]
print(df)

[[0.02040816 0.06122449 0.         0.08163265 0.04081633]
 [0.12244898 0.16326531 0.10204082 0.18367347 0.14285714]
 [0.2244898  0.26530612 0.20408163 0.28571429 0.24489796]
 [0.32653061 0.36734694 0.30612245 0.3877551  0.34693878]
 [0.42857143 0.46938776 0.40816327 0.48979592 0.44897959]
 [0.53061224 0.57142857 0.51020408 0.59183673 0.55102041]
 [0.63265306 0.67346939 0.6122449  0.69387755 0.65306122]
 [0.73469388 0.7755102  0.71428571 0.79591837 0.75510204]
 [0.83673469 0.87755102 0.81632653 0.89795918 0.85714286]
 [0.93877551 0.97959184 0.91836735 1.         0.95918367]
 [1.01449275 1.04347826 1.         1.05797101 1.02898551]
 [1.08695652 1.11594203 1.07246377 1.13043478 1.10144928]
 [1.15942029 1.1884058  1.14492754 1.20289855 1.17391304]
 [1.23188406 1.26086957 1.2173913  1.27536232 1.24637681]
 [1.30434783 1.33333333 1.28985507 1.34782609 1.31884058]
 [1.37681159 1.4057971  1.36231884 1.42028986 1.39130435]
 [1.44927536 1.47826087 1.43478261 1.49275362 1.46376812]
 [1.52173913 1

### Part 2: Panda

In [ ]:
import pandas as pd

Hur många regioner finns med i data?
Lista regionerna i bokstavsordning
Vad är invånarantalet i varje region
Hur många brott begicks i varje region
Skapa en dataframe på de områden  med de 10 högsta antalet överfall.
Lägg till en kolumn i dataframen som visar % antal överfall i området jämfört med invånarantal i området
Skapa en ny dataframe som innehåller antalet områden som finns av de olika typerna av urban area. Ledtråd: groupby
Ta reda på hur många områden hade population men inga överfall. Jämfört totala populationen i dessa med totala poplulationen i deras region.
Räkna antalet områden som inte har någon data på överfall eller invånare.
VG: Skapa en ny dataframe med 10  områderna med mer än 5000 invånare, men har de lägsta överfallen per invånare. 
VG: Skapa en ny dataframe som innehåller % överfall i regionen jämfört med antalet invånare i regionen.  
VG: Lägg till en ny kolumn i dataframen som visar % antal överfall per region


In [ ]:
assults = pd.read_csv('assults.csv')
assults

### 1. Hur många regioner finns med i data?

In [ ]:
print(len(assults.drop_duplicates('Region_2013_label')))

### 2. Lista regionerna i bokstavsordning

In [ ]:
df = assults.sort_values(by=['Region_2013_label']).drop_duplicates('Region_2013_label')
df['Region_2013_label']

### 3. Vad är invånarantalet i varje region

In [ ]:
df1 = assults.groupby('Region_2013_label')[['Population_mid_point_2015']].sum()
df1

### 4.Hur många brott begicks i varje region.

In [ ]:
df1 = assults.groupby('Region_2013_label')[['Victimisations_calendar_year_2015']].sum()
df1

### 5.Skapa en dataframe på de områden  med de 10 högsta antalet överfall.

In [ ]:
df1['Victimisations_calendar_year_2015'].nlargest(10)

### 6.Lägg till en kolumn i dataframen som visar % antal överfall i området jämfört medinvånarantal i området

In [ ]:
procent = assults['Victimisations_calendar_year_2015'] / assults['Population_mid_point_2015']
assults["Procent_Victimisations_by_Population"] = procent
assults

### 7.Skapa en ny dataframe som innehåller antalet områden som finns av de olika typerna avurban area. Ledtråd:groupby

In [ ]:
df = assults.groupby('Urban_area_type')[['Urban_area_2013_label']].count()
df

### 8.Ta reda på hur många områden hade population men inga överfall. Jämfört totalapopulationen i dessa med totala poplulationen i deras region.

In [ ]:
df1 = assults[(assults['Victimisations_calendar_year_2015'] == 0)&(assults['Population_mid_point_2015'] != 0)]
df2 = df1.groupby('Area_unit_2013_label')[['Area_unit_2013_label','Population_mid_point_2015','Region_2013_label']]

print('Antalet områden hade population men inga överfall är: ',len(df2))



In [ ]:
totalapopulationen_i_varje_område = df1.groupby('Area_unit_2013_label')[['Population_mid_point_2015']].sum()
totalapopulationen_i_varje_område

In [ ]:
totalapoplulationen_i_varje_region = assults.groupby('Region_2013_label')[['Population_mid_point_2015']].sum()
totalapoplulationen_i_varje_region

### 9.Räkna antalet områden som inte har ån data på överfall eller invånare.

In [ ]:
df1 = assults[(assults['Victimisations_calendar_year_2015'] == 0)&(assults['Population_mid_point_2015'] == 0)]
df2 = df1.groupby('Area_unit_2013_label')[['Area_unit_2013_label','Population_mid_point_2015','Region_2013_label']]

print('Antalet områden som inte har någon data på överfall eller invånare är: ',len(df2))

### Part 3: Utforskning/analys

Minst 500 rader, 5 Kolumner i ditt valda dataset

#### Step 1: Välj dataset

Hitta ett intressant dataset. Det valda datasettet måste vara i CSV format,  ha minst 500 rader och 5 kolumner. 
Ladda ner datasetet med pandas read_csv funktion och en url (se nedan). Alternativt i inlämningen skicka med datasettet.

In [ ]:
data = pd.read_csv('healthcare_stroke_dataset.csv')

#### Step 2: Data preparation och Cleaning

Ladda in dataset in i en dataframe med pandas. 
Behandla missade data, icke-korrekt data och fel data.
Gör andra steg som behövs (gör om sträng datum till riktiga datum, skapa fler kolumner, slå ihop datasets osv).
Summera hur datasetet ser ut i nuvarande läge i dina markdowns. Storlek, kolumner, kategori typer (qualitative vs. quantitative), kvalitet på data, fång osv.

### Ta en första titt på datan

In [ ]:
# I can see missing data in (bmi-Column) already!
data.head()
test_data = data.copy()
#data = 5110 rows × 14 columns

### Hur många procent av raderna som innehåller streck/ minus tecken '-' då indikerar det att det finns inte något data i smoking_status columnen.

In [ ]:
test_data.loc[(test_data['smoking_status'] == '-') , 'missing_data'] = False  
test_data.loc[(data['smoking_status'] != '-') , 'missing_data'] = True

miss = test_data.groupby('missing_data')[['missing_data']].count()
miss

In [ ]:
#rows = 5110

print('Andelen av Smoking_data kolumn som inte har någon data är:', (1544/5110)*100)

### 30% är för mycket för att kunna använda, det är bättre att inte använda Smoking_data alls annars får vi för mycket fel.

### Hur många rader har inte fullständig data innehåller NaN?

In [ ]:
# get the number of missing data points per column
missing_values_count = data.isnull().sum()

# look at the # of missing points in the first ten columns
missing_values_count[0:13]

# There is 201 missing data in bmi 

### Hur många procent av raderna har NaN i vår dataset

In [ ]:
# how many total missing values do we have?
total_cells = np.product(data.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
percent_missing = (total_missing/total_cells) * 100
print(percent_missing)

### Resultatet är 0.30 %. det är för lite så jag antar det är ok att ta bort.

### Radera rader som inte innehåller data

In [ ]:
# remove all the rows that contain a missing value
no_missing_data = data.dropna()

# get the number of missing data points per column
missing_values_count = no_missing_data.isnull().sum()

# look at the # of missing points in the first ten columns
missing_values_count[0:13]

In [ ]:
no_missing_data.head()

### Ändring av datum format

In [ ]:
no_missing_data['date'] = pd.to_datetime(no_missing_data['date'])
no_missing_data

### Ta reda på datatyperna i vår dataset

In [ ]:
print(no_missing_data.dtypes)

### Lägg till en ny kolumn som heter risk

In [ ]:
#conditions 
def conditions(s):
    risk = 0
    if s['age'] >= 50:
        risk += 1
    if s['hypertension'] > 0:
        risk += 1
    if s['heart_disease'] > 0:
        risk += 1
    if s['bmi'] > 25:
        risk += 1
    if s['avg_glucose_level'] >= 99:
        risk += 1
    #if s['smoking_status'] == 'smokes' or s['smoking_status'] == 'formerly smoked':
        #risk += 1
    if s['stroke'] > 0:
        risk += 1
    return risk

no_missing_data['risk'] = no_missing_data.apply(conditions, axis=1)
no_missing_data
copy_no_missing_data = no_missing_data.copy()

### Ändra så att talen blir mellan 0 och 1

In [ ]:
no_missing_data['age'] = no_missing_data['age'].apply(lambda x: 1 if x >= 50 else 0)
no_missing_data['avg_glucose_level'] = no_missing_data['avg_glucose_level'].apply(lambda x: 1 if x >= 99 else 0)
no_missing_data['bmi'] = no_missing_data['bmi'].apply(lambda x: 1 if x >= 25 else 0)
#no_missing_data['smoking_status'] = no_missing_data['smoking_status'].apply(lambda x: 1 if x == 'smokes'or x == 'formerly smoked'  else 0)
no_missing_data

#### Step 3: Undersökande analys och visualisering

Undersök data genom analysera (mean, sum, range osv)  intressant statistik i numeriska kolumnerna.
Undersök distributions av numeriska kolumner genom histogram osv
Undersök relationen mellan kolumner med scatter plots, bar chars osv.
Notera intressanta upptäckter i din markdown.

### Kön fördelning i Procent

In [ ]:
#how many male in this study
All_male = len(no_missing_data[(no_missing_data['gender'] == 'Male')])
# how many total missing values do we have?
total_cells = np.product(data.shape)

# percent of data that is missing
percent_male = (All_male/total_cells) * 100
precent_female = (1-(percent_male/100))*100


print('Total:',total_cells)
print('male:',All_male)
print('female:', total_cells-All_male)
print('percent_female:',precent_female)
print('percent_male:', percent_male)

### Antalet procent för personer som är under 30 år gammla

In [ ]:
age_under_30 = no_missing_data[(no_missing_data['age'] < 30)]
len(age_under_30)/total_cells

### Medel Åldern i vår datasett

In [ ]:
mean_age = no_missing_data['age'].mean()
mean_age

### Hur många patienter som hammnat under samma risk kategori?

In [ ]:
quantity_patients_in_same_risk_group = no_missing_data.groupby('risk')[['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke','risk']]
quantity_patients_in_same_risk_group.sum() 

In [ ]:
antalet_patienter_i_varej_grupp = no_missing_data.groupby('risk')[['risk']]
antalet_patienter_i_varej_grupp.count()

### Histogram

In [ ]:
bins = [1, 2, 3, 4, 5, 6, 7]
plt.hist(no_missing_data['risk'],bins=bins)

plt.ylabel('Antal')
plt.xlabel('RISK')
plt.title('Antalet personer som har hamnat i samma risk kategory')
plt.show()

#### I Histogramet ser ut som att antalt personer med 1 och 2 risker är mest drappade av stroke 

### Undersöking av relationen mellan kolumner med scatter plots, bar chars

#### Step 4: För VG - fråga och svara på 4 intressanta frågor om datan

In [ ]:
age_risk = no_missing_data.plot.scatter(x = 'age', y = 'risk', c = 'DarkBlue')
age_risk_hypertension = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='hypertension', colormap='viridis')
age_risk_heart_disease = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='heart_disease', colormap='viridis')
age_risk_avg_glucose_level = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='avg_glucose_level', colormap='viridis')
age_risk_bmi = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='bmi', colormap='viridis')
#age_risk_smoking_status = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='smoking_status', colormap='viridis')
age_risk_stroke = no_missing_data.plot.scatter(x = 'age', y = 'risk', c='stroke', colormap='viridis')

In [ ]:
#ax = copy_no_missing_data.plot.barh( x = 'age', y = 'risk')
#ax1 = copy_no_missing_data.plot.bar(x = 'age', y = 'stroke')y
#Det tar för lång tid att plotta.

#### Step 5: Summera dina slutsatser & Skriv ett avslut.

#### Scatter diagramen visar ålder i två grupper som är under och lika med 50 år och över 50 år på x axeln och risk på y axeln passerat på olika sjukdomar/livstil. Vi ser att BMI är hög bland nästan alla åldrar som har fått stroke, vi ser också samma varjant när det gäller avg_glucose_level, men resten ser ut som att åldern som spelar stor roll. man hade kunnat hitta bättre samband bland olika åldrar, sjukdomar och livsstil på ett bättre sett genom till exempel att använda numerisk_logaritmen för att kunna se hur varje kolumn påverkar dem andra.

#### Avslutningsvis pandas är mycket kraftfull och intressant,men som sagt datan måste vara korrekt och fel fri. Det är mycket bra att man kan visualisera data på olika sätt för att kuna gämföra och hitta samband. Nu vill jag använda den för att analysera olika intresanta aktien man kan investera i.

In [ ]:
import seaborn as sns
no_missing_data.drop(['id'] , axis=1, inplace=True)
print(no_missing_data.corr())
sns.heatmap(no_missing_data.corr())